GET http://localhost:5000/weatherforecast

###
GET https://localhost:7150/api/Products

### 
GET https://localhost:7150/api/Products?pageindex=1&pagesize=2

####
### Client site testing

/// Test Identity

POST https://localhost:7150/api/Authentication/register-user
Content-Type: application/json

{
  "Email": "mikeo3@mialco.net",
  "UserName": "mikeo1",
  "Password":"*",
  "ConfirmPassword":"*",
  "FirstName":"Mike",
  "LastName":"Ola"
}

### Login
POST https://localhost:7150/api/Authentication/login-user
Content-Type: application/json

{"userName":"mikeo5@mialco.com","password":"Myverysolid!1"}


# {
#  "username" : "mikeo1",
# "password":"Mikeo1@mialco.com"
# }

###

// My Key is : Amcoman@MialcoAtLeast16character-Long-key
# Test Categories
###M

### Refresh Token

POST https://localhost:7150/api/Authentication/refresh-token
Content-Type: application/json

{
  "token": 
  "refreshToken": 
}



### Test categories
 
GET https://localhost:7150/api/categories
Authorization: Bearer 







