GET http://localhost:5000/weatherforecast

###
GET https://localhost:7150/api/Products

### 
GET https://localhost:7150/api/Products?pageindex=1&pagesize=2

####
### Client site testing

/// Test Identity

POST https://localhost:7150/api/Authentication/register-user
Accept: application/json

{
  "Email": "mikeo@mialco.net",
  UserName: "mikeo",
  "Password:"MyGreatPassword"
}

### Login
POST https://localhost:7150/api/Authentication/login-user
Content-Type: application/json

{
 "username" : "mikeo1",
"password":"Mikeo1"
}


###

// My Key is : Amcoman@MialcoAtLeast16character-Long-key
# Test Categories
###

### Refresh Token

POST https://localhost:7150/api/Authentication/refresh-token
Content-Type: application/json

{
  "token": 
  "refreshToken": 
}



### Test categories
 
GET https://localhost:7150/api/categories
Authorization: Bearer 




