GET http://localhost:5000/weatherforecast

###
GET https://localhost:7150/api/Products

### 
GET https://localhost:7150/api/Products?pageindex=1&pagesize=2

####
### Client site testing

/// Test Identity

POST https://localhost:7150/api/Authentication/register-user
Accept: application/json

{
  "Email": "mikeo@mialco.net",
  UserName: "mikeo",
  "Password:"MyGreatPassword"
}

### Login
POST https://localhost:7150/api/Authentication/login-user
Content-Type: application/json

{
 "username" : "mikeo1",
"password":"Mikeo1@mialco.com"
}


###
{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoibWlrZW8xIiwianRpIjpbImY2NDIwN2MzLTZmODEtNDBhMy04ZDUzLTI0ZjU0N2M5OGZmMCIsImZlYmM4ODlhLTkzNzQtNGY0NS1iNTFkLThiNzRkY2YzZDBkOSJdLCJlbWFpbCI6Im1pa2VvMUBtaWFsY28uY29tIiwic3ViIjoibWlrZW8xQG1pYWxjby5jb20iLCJleHAiOjE3MDc4MDQ2NjksImlzcyI6Im1pYWxjby5uZXQiLCJhdWQiOiJtaWFsY28ubmV0In0.jJV4iIZOVac2wHwsQDch-zJZ7kDu9xwhTpuKkfVifn8",
  "refreshToken": "b9b15e12-5761-4a6a-8ebc-79a626c893c7-e84e182c-544b-4376-a33e-12397ed4b045",
  "expiresAt": "2024-02-13T06:11:09Z"
}

// My Key is : Amcoman@MialcoAtLeast16character-Long-key
# Test Categories
###
GET https://localhost:7150/api/categories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtaWtlbzFAbWlhbGNvLmNvbSIsImp0aSI6ImIzOWM2ZmM0LTg2ZmQtNGIyNC1iNTQ3LTZlOTQwZWZkM2Q2ZCIsImVtYWlsIjoibWlrZW8xQG1pYWxjby5jb20iLCJ1aWQiOiJkOTRlMDMzNi1mYzBkLTQ4ZmEtYmQ4MS04MjdjOTYyNTc4YTQiLCJleHAiOjE3MDc5NzU1MjIsImlzcyI6Im1pYWxjby5uZXQiLCJhdWQiOiJtaWFsY28ubmV0In0.6aTj5NsIcqQWd4e42ULWxkMzyWs_aTZOV3TKgSYmo6o





